[package]
name = "dodo_payments"
version = "0.1.0"
edition = "2024"
exclude = ["./examples"]

[dependencies]
reqwest = "0.12.23"
serde = "1.0.223"
serde_json = "1.0.145"
serde_with = "3.14.0"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
